---
apiVersion: v1
kind: Namespace
metadata:
  name: clips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clips
  namespace: clips
  labels:
    app: clips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clips
  template:
    metadata:
      labels:
        app: clips
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: clips
        image: antitux/clips:latest
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: clips
  namespace: clips
  labels:
    service: clips
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: clips
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clips-ingress
  namespace: clips
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: clips.antx.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: clips
              port:
                number: 80
  tls:
  - hosts:
    - 'clips.antx.dev'
    secretName: myingress-cert