name: build

on:
  workflow_dispatch:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Get SHA
      run: |
        echo ${{ env.GITHUB_SHA }}
    - name: Login to Docker Repo
      uses: docker/login-action@v3
      with:
        registry: r.antx.dev
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build and Push ${{ vars.PROJECT_NAME }}
      uses: docker/build-push-action@v6
      with:
        push: true
        no-cache: true
        tags: |
          r.antx.dev/${{ vars.PROJECT_NAME }}:latest
          r.antx.dev/${{ vars.PROJECT_NAME }}:${{ env.GITHUB_SHA }}
